version: 0.2

env:
  variables:
    ACCOUNT_ID: 235494798709
    REGION: us-east-1
    REPO_NAME: test
    IMAGE_TAG: v12
    IMAGE_URI: 235494798709.dkr.ecr.us-east-1.amazonaws.com/test:v12
    SONAR_PROJECT_KEY: capstone-project-sonar
    SONAR_HOST_URL: http://44.206.246.48
    SONAR_TOKEN: sqp_53a12545f0fd992081b5d8c63bf7c232ae16e67e

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - echo Installing Maven and Docker...
      - yum install -y maven docker
      - echo Installing Trivy...
      #- wget https://github.com/aquasecurity/trivy/releases/download/v0.63.0/trivy_0.63.0_Linux-64bit.tar.gz
      #- tar -zxvf trivy_0.63.0_Linux-64bit.tar.gz
      #- mv trivy /usr/local/bin/

  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $REGION | docker login --username AWS --password-stdin $ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com

  build:
    commands:
      - echo Running SonarQube analysis...
      - cd app-tier
      - mvn clean package -DskipTests
      #- mvn clean verify sonar:sonar -Dsonar.projectKey=$SONAR_PROJECT_KEY -Dsonar.host.url=$SONAR_HOST_URL -Dsonar.login=$SONAR_TOKEN -DskipTests
      - echo Building Docker image...
      - docker build -t $REPO_NAME:$IMAGE_TAG .
      - docker tag $REPO_NAME:$IMAGE_TAG $IMAGE_URI
      - cd ..

  post_build:
    commands:
      - echo Pushing image to Amazon ECR...
      - docker push $IMAGE_URI
      #- echo Scanning image with Trivy...
      #- trivy image $IMAGE_URI --severity CRITICAL,HIGH || true
      - echo Preparing Kubernetes manifests...
      - mkdir -p k8s-out
      - sed "s|IMAGE_PLACEHOLDER|$IMAGE_URI|g" k8s/deployment.yaml > k8s-out/deployment.yaml
      - cp k8s/service.yaml k8s-out/service.yaml
      - echo Done preparing artifacts.
                        
artifacts:
  base-directory: k8s-out
  files:
    - deployment.yaml
    - service.yaml
