apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app
  labels:
    app: todo-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: todo-app
  template:
    metadata:
      labels:
        app: todo-app
    spec:
      containers:
        - name: todo-app
          image: 235494798709.dkr.ecr.us-west-1.amazonaws.com/test:v12
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://mysqldatabase.cdeyuc8yoid6.us-east-1.rds.amazonaws.com:3306/todo
            - name: SPRING_DATASOURCE_USERNAME
              value: admin
            - name: SPRING_DATASOURCE_PASSWORD
              value: adminadmin
            - name: SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT
              value: org.hibernate.dialect.MySQL8Dialect
